// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAp7bGTRSZDgpLer58ngO84IDF_lrrgIw',
    appId: '1:803081167503:web:512743065023beaf8046fa',
    messagingSenderId: '803081167503',
    projectId: 'spotify-flutter-512c5',
    authDomain: 'spotify-flutter-512c5.firebaseapp.com',
    storageBucket: 'spotify-flutter-512c5.appspot.com',
    measurementId: 'G-T6HT94YF89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCFAswaTLtqfghmYKKCUIsmAYsCCuVuoc',
    appId: '1:803081167503:android:d5cf230fb1687a008046fa',
    messagingSenderId: '803081167503',
    projectId: 'spotify-flutter-512c5',
    storageBucket: 'spotify-flutter-512c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB1_58LAOx8EkbinFXcwBF-JqLBSRmnOg',
    appId: '1:803081167503:ios:7b4e08c1932510ce8046fa',
    messagingSenderId: '803081167503',
    projectId: 'spotify-flutter-512c5',
    storageBucket: 'spotify-flutter-512c5.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB1_58LAOx8EkbinFXcwBF-JqLBSRmnOg',
    appId: '1:803081167503:ios:7b4e08c1932510ce8046fa',
    messagingSenderId: '803081167503',
    projectId: 'spotify-flutter-512c5',
    storageBucket: 'spotify-flutter-512c5.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAp7bGTRSZDgpLer58ngO84IDF_lrrgIw',
    appId: '1:803081167503:web:d8965ab2783bda208046fa',
    messagingSenderId: '803081167503',
    projectId: 'spotify-flutter-512c5',
    authDomain: 'spotify-flutter-512c5.firebaseapp.com',
    storageBucket: 'spotify-flutter-512c5.appspot.com',
    measurementId: 'G-7NBCGGSPRP',
  );
}
